VALID_IMAGE_PATH = ''
OUTPUT_DIR = './output'
OUTPUT_CREATED_IMAGE = './output/created_image.png'
OUTPUT_CREATED_IMAGE_FROM_TUPLE = './output/created_image_from_tuple.png'
OUTPUT_CREATED_IMAGE_FROM_DEFAULT_PARAMS = './output/created_image_from_default_params.png'